backend:
  name: git-gateway
  branch: main  # Sesuaikan dengan nama branch di GitHub (bisa "master" atau "main")

media_folder: "images/uploads"  # Folder untuk menyimpan gambar
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"  # Tempat menyimpan artikel Markdown
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
